apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deploy
  namespace: argoarlen
  labels:
    app: nginx-app
spec:
  selector:
    matchLabels:
      app: nginx-app
  replicas: 2
  template:
    metadata:
      labels:
        app: nginx-app
    spec:
      containers:
        - name: nginx-app-john
          image: arlen2001/arlen2:latest
          ports:
            - containerPort: 8080